import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Orbitron } from "next/font/google";
import "./globals.css";

const orbitron = Orbitron({
  weight: "900",
  subsets: ["latin"],
  variable: "--orbitron",
});

const inter = Inter({ subsets: ["latin"], variable: "--inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.variable} ${orbitron.variable} `}
        style={{ width: " 100%", backgroundColor: "white" }}
      >
        {children}
      </body>
    </html>
  );
}

//${inter.variable}
